version: '3.1'
services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: teamcity_db
    volumes:
      - ./data/mysql:/var/lib/mysql
    user: "${UID}:${GID}"

  teamcity:
    image: jetbrains/teamcity-server:2021.1.2
    container_name: teamcity
    restart: always
    volumes:
      - ./data/tc/tc-data:/data/teamcity_server/datadir
      - ./data/tc/tc-logs:/opt/teamcity/logs
    depends_on:
      - db

  nginx:
    image: nginx:1.21
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/tc.crt:/etc/nginx/tc.crt
      - ./config/nginx/tc.key:/etc/nginx/tc.key
    links:
      - "teamcity:teamcity"
