version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: teamcity_db
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    user: 1000:1000

  teamcity:
    image: jetbrains/teamcity-server
    container_name: teamcity
    ports:
      - "8111:8111"
    volumes:
      - ./tc-data:/data/teamcity_server/datadir
      - ./tc-logs:/opt/teamcity/logs
    depends_on:
      - db

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./tc.crt:/etc/nginx/tc.crt
      - ./tc.key:/etc/nginx/tc.key
    links:
      - "teamcity:teamcity"
